In [36]:
import pandas as pd
import numpy as np
from functools import reduce

In [29]:
def read_csvs(path, file1, file2):
    f1 = f'{path}/{file1}'
    f2 = f'{path}/{file2}'
    return pd.read_csv(f1), pd.read_csv(f2)

In [27]:
common_path = '/Users/neil/Desktop/GaTech.nosync/Fall2025/CSE 6740/WiFOP/data/raw/power_ca_jul2023/'

In [30]:
prec_df1, prec_df2 = read_csvs(common_path, 'PRECTOT_tile1.csv', 'PRECTOT_tile2.csv')
ps_df1, ps_df2 = read_csvs(common_path, 'PS_tile1.csv', 'PS_tile2.csv')
rh_df1, rh_df2 = read_csvs(common_path, 'RH2M_tile1.csv', 'RH2M_tile2.csv')
t2m_df1, t2m_df2 = read_csvs(common_path, 'T2M_tile1.csv', 'T2M_tile2.csv')
ws_df1, ws_df2 = read_csvs(common_path, 'WS10M_tile1.csv', 'WS10M_tile2.csv')

In [38]:
dfs1 = [prec_df1, ps_df1, rh_df1, t2m_df1, ws_df1]
tile1_merged = reduce(lambda left, right: pd.merge(left, right, on=['LAT', 'LON', 'YEAR', 'DOY'], how='inner'), dfs1)

In [ ]:
tile1_merged

       LAT      LON  YEAR  DOY  PRECTOTCORR      PS   RH2M    T2M  WS10M
0     32.5 -124.375  2023  182          0.0  101.56  95.15  15.14   7.11
1     32.5 -123.750  2023  182          0.0  101.50  95.73  15.10   7.23
2     32.5 -123.125  2023  182          0.0  101.45  96.26  15.02   7.17
3     32.5 -122.500  2023  182          0.0  101.39  96.83  14.87   6.92
4     32.5 -121.875  2023  182          0.0  101.35  97.13  14.77   6.74
...    ...      ...   ...  ...          ...     ...    ...    ...    ...
4955  42.0 -122.500  2023  212          0.0   88.20  43.63  20.56   1.74
4956  42.0 -121.875  2023  212          0.0   86.26  44.16  20.56   2.13
4957  42.0 -121.250  2023  212          0.0   86.05  39.17  21.42   2.69
4958  42.0 -120.625  2023  212          0.0   84.13  38.96  20.35   2.70
4959  42.0 -120.000  2023  212          0.0   83.41  34.36  20.91   2.81

[4960 rows x 9 columns]

In [40]:
dfs2 = [prec_df2, ps_df2, rh_df2, t2m_df2, ws_df2]
tile2_merged = reduce(lambda left, right: pd.merge(left, right, on=['LAT', 'LON', 'YEAR', 'DOY'], how='inner'), dfs2)

In [41]:
tile2_merged

       LAT      LON  YEAR  DOY  PRECTOTCORR      PS   RH2M    T2M  WS10M
0     32.5 -119.375  2023  182          0.0  101.22  97.27  13.54   2.60
1     32.5 -118.750  2023  182          0.0  101.22  96.01  14.08   2.61
2     32.5 -118.125  2023  182          0.0  101.17  96.33  14.67   2.09
3     32.5 -117.500  2023  182          0.0  100.97  93.36  16.09   2.33
4     32.5 -116.875  2023  182          0.0   96.66  53.60  23.12   1.86
...    ...      ...   ...  ...          ...     ...    ...    ...    ...
5575  42.0 -116.875  2023  212          0.0   83.63  22.52  25.14   3.37
5576  42.0 -116.250  2023  212          0.0   82.78  25.01  25.22   3.34
5577  42.0 -115.625  2023  212          0.0   81.94  26.29  24.95   3.08
5578  42.0 -115.000  2023  212          0.0   81.72  28.24  25.09   2.15
5579  42.0 -114.375  2023  212          0.0   82.58  35.25  25.73   1.89

[5580 rows x 9 columns]

In [49]:
merged_df = pd.concat([tile1_merged, tile2_merged], axis=0, ignore_index=True)

In [50]:
merged_df.shape

(10540, 9)

In [51]:
merged_df.to_csv('NASA_POWER.csv', index=False)