In [1]:
import pandas as pd
import numpy as np
from functools import reduce

In [2]:
def read_csvs(path, file1, file2):
    f1 = f'{path}/{file1}'
    f2 = f'{path}/{file2}'
    return pd.read_csv(f1), pd.read_csv(f2)

In [3]:
common_path = '/Users/neil/Desktop/GaTech.nosync/Fall2025/CSE 6740/WiFOP/src/nasa_power/power_ca_jul_sep2023/'

In [4]:
prec_df1, prec_df2 = read_csvs(common_path, 'PRECTOT_tile1.csv', 'PRECTOT_tile2.csv')
ps_df1, ps_df2 = read_csvs(common_path, 'PS_tile1.csv', 'PS_tile2.csv')
rh_df1, rh_df2 = read_csvs(common_path, 'RH2M_tile1.csv', 'RH2M_tile2.csv')
t2m_df1, t2m_df2 = read_csvs(common_path, 'T2M_tile1.csv', 'T2M_tile2.csv')
ws_df1, ws_df2 = read_csvs(common_path, 'WS10M_tile1.csv', 'WS10M_tile2.csv')

In [5]:
dfs1 = [prec_df1, ps_df1, rh_df1, t2m_df1, ws_df1]
tile1_merged = reduce(lambda left, right: pd.merge(left, right, on=['LAT', 'LON', 'YEAR', 'DOY'], how='inner'), dfs1)

In [6]:
tile1_merged

        LAT      LON  YEAR  DOY  PRECTOTCORR      PS   RH2M    T2M  WS10M
0      32.5 -124.375  2023  182         0.00  101.56  95.15  15.14   7.11
1      32.5 -123.750  2023  182         0.00  101.50  95.73  15.10   7.23
2      32.5 -123.125  2023  182         0.00  101.45  96.26  15.02   7.17
3      32.5 -122.500  2023  182         0.00  101.39  96.83  14.87   6.92
4      32.5 -121.875  2023  182         0.00  101.35  97.13  14.77   6.74
...     ...      ...   ...  ...          ...     ...    ...    ...    ...
14715  42.0 -122.500  2023  273         6.70   87.31  92.22   9.32   2.14
14716  42.0 -121.875  2023  273         6.39   85.29  87.64   9.26   2.75
14717  42.0 -121.250  2023  273         5.28   85.08  79.74   9.64   2.99
14718  42.0 -120.625  2023  273         5.27   83.10  77.45   8.60   2.77
14719  42.0 -120.000  2023  273         6.63   82.38  73.69   8.46   2.79

[14720 rows x 9 columns]

In [7]:
dfs2 = [prec_df2, ps_df2, rh_df2, t2m_df2, ws_df2]
tile2_merged = reduce(lambda left, right: pd.merge(left, right, on=['LAT', 'LON', 'YEAR', 'DOY'], how='inner'), dfs2)

In [8]:
tile2_merged

        LAT      LON  YEAR  DOY  PRECTOTCORR      PS   RH2M    T2M  WS10M
0      32.5 -119.375  2023  182         0.00  101.22  97.27  13.54   2.60
1      32.5 -118.750  2023  182         0.00  101.22  96.01  14.08   2.61
2      32.5 -118.125  2023  182         0.00  101.17  96.33  14.67   2.09
3      32.5 -117.500  2023  182         0.00  100.97  93.36  16.09   2.33
4      32.5 -116.875  2023  182         0.00   96.66  53.60  23.12   1.86
...     ...      ...   ...  ...          ...     ...    ...    ...    ...
16555  42.0 -116.875  2023  273        13.41   82.60  70.29   9.14   3.34
16556  42.0 -116.250  2023  273        10.10   81.70  70.79   8.62   3.33
16557  42.0 -115.625  2023  273         7.72   80.80  67.05   9.75   3.35
16558  42.0 -115.000  2023  273         4.23   80.55  63.71  10.49   2.81
16559  42.0 -114.375  2023  273         1.09   81.43  54.90  12.27   2.70

[16560 rows x 9 columns]

In [9]:
merged_df = pd.concat([tile1_merged, tile2_merged], axis=0, ignore_index=True)

In [10]:
merged_df.shape

(31280, 9)

In [11]:
merged_df.to_csv('NASA_POWER_JUL_SEP2023.csv', index=False)