In [1]:
import pandas as pd
import numpy as np

In [4]:
file = '/Users/neil/Desktop/GaTech.nosync/Fall2025/CSE 6740/WiFOP/src/nasa_power/NASA_POWER_JUL_SEP2023.csv'
df = pd.read_csv(file)

In [5]:
df.head()

    LAT      LON  YEAR  DOY  PRECTOTCORR      PS   RH2M    T2M  WS10M
0  32.5 -124.375  2023  182          0.0  101.56  95.15  15.14   7.11
1  32.5 -123.750  2023  182          0.0  101.50  95.73  15.10   7.23
2  32.5 -123.125  2023  182          0.0  101.45  96.26  15.02   7.17
3  32.5 -122.500  2023  182          0.0  101.39  96.83  14.87   6.92
4  32.5 -121.875  2023  182          0.0  101.35  97.13  14.77   6.74

In [6]:
df["DATE"] = pd.to_datetime(df["YEAR"].astype(int), format="%Y") + pd.to_timedelta(df["DOY"].astype(int) - 1, unit="D")

In [7]:
df['DATE'] = df["DATE"].dt.strftime("%Y-%m-%d")

In [8]:
df.drop(['YEAR', 'DOY'], inplace=True, axis=1)
df

        LAT      LON  PRECTOTCORR      PS   RH2M    T2M  WS10M        DATE
0      32.5 -124.375         0.00  101.56  95.15  15.14   7.11  2023-07-01
1      32.5 -123.750         0.00  101.50  95.73  15.10   7.23  2023-07-01
2      32.5 -123.125         0.00  101.45  96.26  15.02   7.17  2023-07-01
3      32.5 -122.500         0.00  101.39  96.83  14.87   6.92  2023-07-01
4      32.5 -121.875         0.00  101.35  97.13  14.77   6.74  2023-07-01
...     ...      ...          ...     ...    ...    ...    ...         ...
31275  42.0 -116.875        13.41   82.60  70.29   9.14   3.34  2023-09-30
31276  42.0 -116.250        10.10   81.70  70.79   8.62   3.33  2023-09-30
31277  42.0 -115.625         7.72   80.80  67.05   9.75   3.35  2023-09-30
31278  42.0 -115.000         4.23   80.55  63.71  10.49   2.81  2023-09-30
31279  42.0 -114.375         1.09   81.43  54.90  12.27   2.70  2023-09-30

[31280 rows x 8 columns]

In [9]:
df.to_csv('NASA POWER JUL_SEP 2023.csv', index=False)